### ISSUE TITLE
In example, "ReferenceError: WebSocket is not defined"

### ISSUE THREAD

**Issue by mzidian** [zudov/purescript-websocket-simple#13]
$ pulp run
- Building project in/Users/matthewzidian/p/meteor/matcher/purescript/bower_components/purescript-websocket-simple/example
- Build successful.
  /Users/matthewzidian/p/meteor/matcher/purescript/bower_components/purescript-websocket-simple/example/output/WebSocket/foreign.js:12
  var socket = new WebSocket(url, protocols);
                   ^

ReferenceError: WebSocket is not defined
    at /Users/matthewzidian/p/meteor/matcher/purescript/bower_components/purescript-websocket-simple/example/output/WebSocket/foreign.js:12:22
    at /Users/matthewzidian/p/meteor/matcher/purescript/bower_components/purescript-websocket-simple/example/output/Control.Monad.Eff/foreign.js:14:16
    at /Users/matthewzidian/p/meteor/matcher/purescript/bower_components/purescript-websocket-simple/example/output/Control.Monad.Eff/foreign.js:14:20
    at Object.__do (/Users/matthewzidian/p/meteor/matcher/purescript/bower_components/purescript-websocket-simple/example/output/Main/index.js:16:68)
    at Object.<anonymous> (/private/var/folders/x3/pk7mx50x16bg_tv9dlmyf1mr0000gn/T/pulp-run11669-57232-1yzij4v.1onu9s5rk9.js:1:79)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
- ERROR: Subcommand terminated with exit code 1

**Comment by zudov** [comment]
`pulp run` simply runs the example on node.js. Node.js doesn't provide websocket api, hence "Websocket is not defined". Browsers however do.

To run it in the browser, you would need to do something like `pulp browserify -o output/script.js`, and then open an html file which references that `output/script.js` (`example/index.html` does just that).

IIRC, I've also been testing this example with phantomjs.

The good point is that it might worth to integrate with some node library that implements `WebSocket` API, in the same way as `purescript-affjax` seamlessly integrates with `xhr2`.

**Comment by mzidian** [comment]
I see.  I was looking for server side sockets.  I'll fork.  Thanks.

**Comment by zudov** [comment]
A pull request would be welcome.
