### ISSUE TITLE
relax dependency bounds? (purescript 0.10.2)

### ISSUE THREAD

**Issue by mmaz** [zudov/purescript-websocket-simple#16]
Hi, I have `purescript 0.10.2` and `pulp 9.1.0` installed. When initializing a project in an empty directory:

```bash
$ pulp init
$ bower i purescript-websocket-simple --save
```

`bower` was unable to automatically resolve transitive dependencies from the version bounds in `purescript-websocket-simple 0.5.1` against the defaults in `bower.json`:

```
...
  "dependencies": {
    "purescript-console": "^2.0.0"
  },
  "devDependencies": {
    "purescript-psci-support": "^2.0.0"
  }
```

Thanks!

**Comment by zudov** [comment]
Fixed and released now https://github.com/zudov/purescript-websocket-simple/releases/tag/v1.0.0
