### ISSUE TITLE
Register on bower

### ISSUE THREAD

**Issue by honza** [zudov/purescript-websocket-simple#2]
http://bower.io/docs/creating-packages/#register

**Comment by zudov** [comment]
I want to get https://github.com/zudov/purescript-websocket-simple/pull/3 done first and then release it. I hope to make it happen around this week.

It works fine, but the API is not complete, if you want to try it and tell what you think I would very much appreciate it.

**Comment by honza** [comment]
I did try it, and everything worked as expected. Simple and effective!

**Comment by zudov** [comment]
Sorry that it took me a while.

It's now up, check pursuit and bower.

**Comment by honza** [comment]
Yay, thanks! :sparkles:
