### ISSUE TITLE
Purescript 0.13.x won't compile websocket-simple as is...

### ISSUE THREAD

**Issue by afcondon** [zudov/purescript-websocket-simple#26]
There are overlapping class instances due to declaration on line 250...pretty sure it's a copy-paste error and the line should actually be: `derive instance genericMessage :: Generic Message _` 

Happy to provide PR if you want it, didn't do so because i have only checked that this compiles and works in our code rather than trying to understand if it is definitively the required fix

**Comment by safareli** [comment]
It must be copy paste, there is already `derive instance genericReason :: Generic Reason _` so your fix is legit.

**Comment by safareli** [comment]
i.e. Feel free to open the pr 🌮

**Comment by safareli** [comment]
closing #27
